# Generated by Django 5.2.4 on 2025-07-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='burnerlink',
            name='original_url',
        ),
        migrations.AddField(
            model_name='burnerlink',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
